spring:
  application:
    name: core-banking-service
  datasource:
    url: jdbc:mysql://localhost:3306/banking_core_service
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8092

